from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, render_to_response

from .models import Careers, SurveyResponses


def show_data(request):
    author = request.user
    total_surveys = SurveyResponses.objects.filter(author_id=author).count()
    accounting = SurveyResponses.objects.filter(author_id=author, Careers__career='Accounting').count()
    general_business = SurveyResponses.objects.filter(author_id=author, Careers__career='General Business ').count()
    software_development = SurveyResponses.objects.filter(author_id=author, Careers__career='Software Development').count()
    admin_clerical = SurveyResponses.objects.filter(author_id=author, Careers__career='Admin & Clerical').count()
    general_labor = SurveyResponses.objects.filter(author_id=author, Careers__career='General Labor').count()
    pharmaceutical = SurveyResponses.objects.filter(author_id=author, Careers__career='Pharmaceutical').count()
    automotive = SurveyResponses.objects.filter(author_id=author, Careers__career='Automotive').count()
    government = SurveyResponses.objects.filter(author_id=author, Careers__career='Government').count()
    professional_services = SurveyResponses.objects.filter(author_id=author, Careers__career='Professional Services').count()
    banking = SurveyResponses.objects.filter(author_id=author, Careers__career='Banking').count()
    grocery = SurveyResponses.objects.filter(author_id=author, Careers__career='Grocery').count()
    purchasing_procurement = SurveyResponses.objects.filter(author_id=author, Careers__career='Purchasing-Procurement').count()
    biotech = SurveyResponses.objects.filter(author_id=author, Careers__career='Biotech').count()
    health_care = SurveyResponses.objects.filter(author_id=author, Careers__career='Health Care').count()
    qa_quality_control = SurveyResponses.objects.filter(author_id=author, Careers__career='QA-Quality Control').count()
    journalism = SurveyResponses.objects.filter(author_id=author, Careers__career='Journalism').count()
    hotel_hospitality = SurveyResponses.objects.filter(author_id=author, Careers__career='Hotel-Hospitality').count()
    Real_Estate = SurveyResponses.objects.filter(author_id=author, Careers__career='Real Estate').count()
    business_development = SurveyResponses.objects.filter(author_id=author, Careers__career='Business Development').count()
    human_resources = SurveyResponses.objects.filter(author_id=author, Careers__career='Human Resources').count()
    research = SurveyResponses.objects.filter(author_id=author, Careers__career='Research').count()
    construction = SurveyResponses.objects.filter(author_id=author, Careers__career='Construction').count()
    information_technology = SurveyResponses.objects.filter(author_id=author, Careers__career='Information Technology ').count()
    restaurant_food_service = SurveyResponses.objects.filter(author_id=author, Careers__career='Restaurant-Food Service').count()
    consultant = SurveyResponses.objects.filter(author_id=author, Careers__career='Consultant').count()
    installation_repair = SurveyResponses.objects.filter(author_id=author, Careers__career='Installation-Repair ').count()
    retail = SurveyResponses.objects.filter(author_id=author, Careers__career='Retail').count()
    customer_service = SurveyResponses.objects.filter(author_id=author, Careers__career='Customer Service').count()
    insurance = SurveyResponses.objects.filter(author_id=author, Careers__career='Insurance').count()
    sales = SurveyResponses.objects.filter(author_id=author, Careers__career='Sales').count()
    design = SurveyResponses.objects.filter(author_id=author, Careers__career='Design').count()
    inventory = SurveyResponses.objects.filter(author_id=author, Careers__career='Inventory').count()
    science = SurveyResponses.objects.filter(author_id=author, Careers__career='Science').count()
    distribution_shipping = SurveyResponses.objects.filter(author_id=author, Careers__career='Distribution-Shipping').count()
    legal = SurveyResponses.objects.filter(author_id=author, Careers__career='Legal').count()
    skilled_labor_trades = SurveyResponses.objects.filter(author_id=author, Careers__career='Skilled Labor-Trades').count()
    education_teaching = SurveyResponses.objects.filter(author_id=author, Careers__career='Education-Teaching').count()
    legal_admin = SurveyResponses.objects.filter(author_id=author, Careers__career='Legal Admin').count()
    strategy_planning = SurveyResponses.objects.filter(author_id=author, Careers__career='Strategy Planning').count()
    engineering = SurveyResponses.objects.filter(author_id=author, Careers__career='Engineering').count()
    management = SurveyResponses.objects.filter(author_id=author, Careers__career='Management').count()
    supply_chain = SurveyResponses.objects.filter(author_id=author, Careers__career='Supply Chain').count()
    entry_level = SurveyResponses.objects.filter(author_id=author, Careers__career='Entry Level ').count()
    manufacturing = SurveyResponses.objects.filter(author_id=author, Careers__career='Manufacturing').count()
    telecommunications = SurveyResponses.objects.filter(author_id=author, Careers__career='Telecommunications').count()
    executive = SurveyResponses.objects.filter(author_id=author, Careers__career='Executive').count()
    marketing = SurveyResponses.objects.filter(author_id=author, Careers__career='Marketing').count()
    training = SurveyResponses.objects.filter(author_id=author, Careers__career='Training').count()
    facilities = SurveyResponses.objects.filter(author_id=author, Careers__career='Facilities').count()
    media = SurveyResponses.objects.filter(author_id=author, Careers__career='Media').count()
    newspaper = SurveyResponses.objects.filter(author_id=author, Careers__career='Newspaper').count()
    transportation = SurveyResponses.objects.filter(author_id=author, Careers__career='Transportation').count()
    finance = SurveyResponses.objects.filter(author_id=author, Careers__career='Finance').count()
    nonprofit = SurveyResponses.objects.filter(author_id=author, Careers__career='Nonprofit').count()
    social_services = SurveyResponses.objects.filter(author_id=author, Careers__career='Social Services').count()
    warehouse = SurveyResponses.objects.filter(author_id=author, Careers__career='Warehouse').count()
    other = SurveyResponses.objects.filter(author_id=author, Careers__career='Other').count()